---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: screego-secret
  namespace: screego
spec:
  encryptedData:
    SCREEGO_SECRET: AgBx1fmOLqgaKh/bLdTP8nodKIyXXCqsMvnK9B6b6SRfi4eRwUV85PVm7eqI8dlQhYKcM54SJYP/hgMWlXEvUAuAcMOsTQIjKgIvewvPf7y7OdW0OvxEX6KGex+mzbC7T7L4BMZAUIZy9py2Oce+2eVi6LqCxs7gto3NPK0kSBYUivsKTAm/JXQxFzs6PPva27CMIJsq1eLL2z5l1cFZ9KSJRDAyV7o1qSrkS56VmVCya2EU3Zl5aybcImPfpNYY+jLEJ1Od9PRI9MpNKsdCDyVIZF3BlPFKBwDCz+cGs/USQxZ67yfyhuHSSraqe6HWKVH1OCFcb+H3L0Kf11jucgTqRoKPMac264IQ9d2jWs0zTy3JGUOgO4uLXcZ7Qe267TiwjPiY4zI+uSoU3hd1Pgg8G4al5hnVOYme6FKkhar4fdG5M0wdTxup9Oar9JiPwy+5zQsHjsEz1cVfMKqpNjRG6eCyb5wP9ZknylAoX5pa0f6QRWW4S3vP5mCmTM08zBYNPRDMRJ9g5Vr54O2hlHrLG+xALphzK90+q0absXA4fUPSUneqgQbY72tcYOuR3Pjd3ywaKyxZDJeeabC9q8QmBLS6z9GSquqvZ9hBC6TXpb5hxgrl6gyzEP4N09BVvPbTVCdNjuAgoQg1VdOUYNJ9t3R0k6mUuyG8cAdXqiJvLvWo5yR3D5ubsjeEw1Ghj98ilM1BLDIrrnKX0GzrbIdutMj9aTNlTfzZhznV913NXAEtkiFWFEhhQf8eBOZrffbJjWD3YtqOHdau9yNhBPA3
    users.passwd: AgA/RDVgRHkCNvvD2/34l9VThIOsqtuIu1xLOx/wcWtGoocTrS47S8g88OV5Fw2heJ9vH/errBCMAxnLMmQH16H8PBhPDaLLDI3cgoxNNmJR8OGj28jLpQtNHliPKGy9ULV82AUWfGK+BQXKQD89SK0hp9b7Py1tt1sFmfOD5GBj3H/b0WJqBFgfeoSTMpxvh85+fmYWqSeFZUMubOknt3QfmasRz9GRFvYHa3fpXNpW7X1mIUe7DVRpV0I2YqHN8Dx2fngReYdZ8SvQhq2UxckzbR3kGzWytwAWH/OPNtgVWOl6KWjP55hJSUtGlxAQpYTfHgQBYYrFmnSHNRApCLofErLjaNC1jPVTJzsOk7wjhs/tsJmYmI8ss2OcQRZp/iJtzP5idA8ehtU6SADOcOkt1/N/AhQmTpMNvgsbGaduihvaGryPjvVeBYOdeqoyVZX+EWa+KDJ61evfMIjLIfQnu1/D5O4tfretcXrAk6ReKmrj36HoNv+TBT9yTiT/IsPttksCc59Ytmxh0sF3HESQ5uEA9UfUMC/P6O4X+i7ZkVumKOM7STSyYojO4u07obX/EsiSOGP0sSZlzIsoIRmiTK2shUEwB/qEq3i+XZgaGaNpieyNYsr+aj79ack1K1igp4HyZj85c7qV5vLvrib2v7dH0L6Rsmp3PUCh82b0fBT67U0RWRifMRS5KaYc0nKGW/Pj+2PmcPBSmU/qXjFeGQ7bkreTwhlBQhkYx54GxtfjgqOcSRpVxhy/zsk6SSF1QrLmEeb4Ti+/0qQTPbqI/TlXDUo=
  template:
    metadata:
      name: screego-secret
      namespace: screego
    type: Opaque
